[2023-09-01T23:24:32.589+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: website_crawler.write_to_file scheduled__2023-08-31T00:00:00+00:00 [queued]>
[2023-09-01T23:24:32.598+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: website_crawler.write_to_file scheduled__2023-08-31T00:00:00+00:00 [queued]>
[2023-09-01T23:24:32.599+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-09-01T23:24:32.616+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): write_to_file> on 2023-08-31 00:00:00+00:00
[2023-09-01T23:24:32.623+0000] {standard_task_runner.py:57} INFO - Started process 65 to run task
[2023-09-01T23:24:32.630+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'website_crawler', 'write_to_file', 'scheduled__2023-08-31T00:00:00+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/crawl_data_using_BeautifulSoup.py', '--cfg-path', '/tmp/tmpiw3bigry']
[2023-09-01T23:24:32.636+0000] {standard_task_runner.py:85} INFO - Job 192: Subtask write_to_file
[2023-09-01T23:24:32.735+0000] {task_command.py:415} INFO - Running <TaskInstance: website_crawler.write_to_file scheduled__2023-08-31T00:00:00+00:00 [running]> on host 200bc7f91af2
[2023-09-01T23:24:32.852+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='website_crawler' AIRFLOW_CTX_TASK_ID='write_to_file' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-31T00:00:00+00:00'
[2023-09-01T23:24:32.856+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-01T23:24:32.858+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    touch /Users/nguyenngocanh/Desktop/cohost\\ AI/dags/test.txt\n    echo abc > /Users/nguyenngocanh/Desktop/cohost\\ AI/dags/test.txt\n    ']
[2023-09-01T23:24:32.882+0000] {subprocess.py:86} INFO - Output:
[2023-09-01T23:24:32.900+0000] {subprocess.py:93} INFO - touch: cannot touch '/Users/nguyenngocanh/Desktop/cohost AI/dags/test.txt': No such file or directory
[2023-09-01T23:24:32.902+0000] {subprocess.py:93} INFO - /bin/bash: line 3: /Users/nguyenngocanh/Desktop/cohost AI/dags/test.txt: No such file or directory
[2023-09-01T23:24:32.904+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-01T23:24:32.925+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-01T23:24:32.931+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=website_crawler, task_id=write_to_file, execution_date=20230831T000000, start_date=20230901T232432, end_date=20230901T232432
[2023-09-01T23:24:32.943+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 192 for task write_to_file (Bash command failed. The command returned a non-zero exit code 1.; 65)
[2023-09-01T23:24:32.962+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-01T23:24:32.984+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
